services:
  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - suzy-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile1
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - suzy-network

networks:
  suzy-network:
    driver: bridge