version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - suzy-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - suzy-network

networks:
  suzy-network:
    driver: bridge